### ISSUE TITLE
what's the difference between `hold_fallback_mode_s` and `hold_modes_down_s`?

### ISSUE THREAD

**Issue by lida2003** [sickgreg/OpenIPC-Adaptive-Link#9]
Hi, I looked into the code, but I didn't get the idea of  `hold_fallback_mode_s` and `hold_modes_down_s`

- Both of them were set to 3 seconds in config file.

https://github.com/sickgreg/OpenIPC-Adaptive-Link/blob/3cc9d3ac00d1024db34d9450d8426b3f9b43c86b/alink.conf#L5-L7

- But it was set to 3/4 in readme

https://github.com/sickgreg/OpenIPC-Adaptive-Link/blob/3cc9d3ac00d1024db34d9450d8426b3f9b43c86b/README.md?plain=1#L79-L81

Can you help to let me know more about this param?

**Comment by sickgreg** [comment]
The config files and their defaults are subject to change with development. 

Fallback profile (999) gets applied when the drone doesn't hear from the ground station for the set number of ms. To avoid excessive changing, there is a min time before it will change back up again. That is hold fallback mode.

Min between changes ms is a limit on how soon after a profile change, either up or down, the next profile change can occur. This is to make sure we've fully applied the profile before attempting to do it again. 

Hold modes down s is the min time before the link speed will be allowed to increase after a profile is applied. This is to help reduce premature changes and excessive changing. There is not a min time for downward changes because if the signal quality drops fast we want the link speed up drop fast too. It can then slowly increase again once we get good stable signal
